tags:
- name: users
  description: users API
- name: hobbies 
  description: hobbies API

paths:
# [GET] users
  /users:
    get:
      tags:
      - users
      summary: Find All Users
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] users
    post:
      tags:
      - users
      summary: Add User
      parameters:
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] users/id
  /users/{id}:
    get:
      tags:
      - users
      summary: Find User By Id
      parameters:
      - name: id
        in: path
        description: User Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] users/id
    put:
      tags:
      - users
      summary: Update User By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] users/id
    delete:
      tags:
      - users
      summary: Delete User By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] Hobbies 
  /hobby:
    get:
      tags:
      - hobbies 
      summary: Find All Hobbies 
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] Hobby 
    post:
      tags:
      - hobbies 
      summary: Add Hobby 
      parameters:
      - name: body
        in: body
        description: Hobbies Data 
        required: true
        schema:
          $ref: '#/definitions/hobbies'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] Get Hobby ID
  /hobby/{hobbyid}:
    get:
      tags:
      - hobbies 
      summary: Find hobby By Id
      parameters:
      - name: hobbyid 
        in: path
        description: Hobby Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] Update Hobby 
    put:
      tags:
      - hobbies 
      summary: Update Hobby By Id
      parameters:
      - name: hobbyid 
        in: path
        description: Hobby Id
        required: true
      - name: body
        in: body
        description: Hobby Data
        required: true
        schema:
          $ref: '#/definitions/hobbies'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] hobby/id
    delete:
      tags:
      - hobbies 
      summary: Delete hobby By Id
      parameters:
      - name: hobbyid
        in: path
        description: Hobby Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'



# [GET] Hobbies By UserID
  /hobby/user/{userid}:
    get:
      tags:
      - hobbies 
      parameters:
      - name: userid 
        in: path
        description: User Id
        required: true
      summary: Find Hobbies  by user ID
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'


# definitions
definitions:
  users:
    type: object
    required:
        - email
        - password
    properties:
      id:
        description: user Id
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password

  hobbies:
    type: object
    required:
        - passionLevel  
    properties:
      id:
        description: hobby Id
      passionLevel:
        type: string
        description: Passion level 
      name :
        type: string
        description: name 
      year:
        type: date
        description: date
      user:
        type: string 
        description: user id

schemes:
 - https
 - http
